server.port=8080 

spring.datasource.url=jdbc:postgresql://ep-steep-brook-aoaf38ce-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_5ZJSpjXVovC3
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=inkly-super-secret-key-please-change-before-going-to-production
jwt.expiry-ms=86400000

cors.allowed-origins=http://localhost:3000